import Link from "next/link";
import { startGymWorkout } from "@/app/gym/actions";
import { PageHeading } from "@/components/page-heading";
import { getGymOverview } from "@/lib/gym/data";

export const metadata = { title: "Gym" };
export const dynamic = "force-dynamic";

export default async function GymPage() {
  const overview = await getGymOverview();
  const activeProgram = overview.programs.find((program) => program.active && !program.archivedAt);
  const nextWorkout = overview.planned[0];
  const lastSession = overview.history[0];
  const hasSetup = Boolean(activeProgram || overview.activeSession || overview.history.length);
  return <>
    <PageHeading eyebrow="Gym · Krafttraining" title="Stärker werden, ohne den Ausdauerplan zu verlieren." description="Programme, geplante Gym-Einheiten und Satz-für-Satz-Tracking bleiben im selben UltraPilot-System." />
    {overview.activeSession ? <section className="mb-5 rounded-[1.5rem] border border-[var(--success)] bg-[var(--success-soft)] p-5"><p className="eyebrow">Workout läuft</p><div className="mt-2 flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-2xl font-black">{overview.activeSession.name}</h2><p className="mt-1 text-sm text-[var(--muted)]">Seit {new Intl.DateTimeFormat("de-DE", { hour: "2-digit", minute: "2-digit" }).format(new Date(overview.activeSession.startedAt))} · Servergespeichert</p></div><Link href={`/gym/workout/${overview.activeSession.id}`} className="primary-button">Training fortsetzen</Link></div></section> : null}
    {!hasSetup ? <section className="card overflow-hidden"><div className="grid gap-8 p-7 lg:grid-cols-[1.2fr_.8fr] lg:p-10"><div><p className="eyebrow">Dein Kraftfundament</p><h2 className="mt-3 text-3xl font-black">Gym-Training einrichten</h2><p className="mt-3 max-w-xl text-sm leading-6 text-[var(--muted)]">Baue dein Programm manuell oder lass dir aus Ziel, Zeit und Equipment einen deterministischen Ausgangsplan erstellen. Danach erscheinen die Einheiten direkt im Bloom-Kalender.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/gym/programs/new" className="primary-button">Program Builder öffnen</Link><Link href="/gym/library" className="secondary-button">245 Übungen entdecken</Link></div></div><div className="rounded-[1.4rem] bg-[var(--surface)] p-5"><p className="text-sm font-black">Was du danach bekommst</p><ul className="mt-4 space-y-3 text-sm text-[var(--ink-soft)]"><li>✓ Gym-Sessions im Wochenkalender</li><li>✓ Schneller mobiler Satz-Logger</li><li>✓ Letzte Performance direkt an der Übung</li><li>✓ PRs und nachvollziehbare Progression</li></ul></div></div></section> : <div className="grid gap-5 xl:grid-cols-[1.3fr_.7fr]"><section className="space-y-5"><article className="card p-6"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">Als Nächstes</p><h2 className="mt-2 text-2xl font-black">{nextWorkout?.title ?? "Kein Gym-Workout geplant"}</h2>{nextWorkout ? <p className="mt-2 text-sm text-[var(--muted)]">{new Intl.DateTimeFormat("de-DE", { weekday: "long", day: "2-digit", month: "2-digit" }).format(new Date(`${nextWorkout.scheduledDate}T12:00:00`))}{nextWorkout.durationMinutes ? ` · ca. ${nextWorkout.durationMinutes} min` : ""}</p> : <p className="mt-2 text-sm text-[var(--muted)]">Plane dein aktives Programm in die nächste Woche ein.</p>}</div>{nextWorkout ? <form action={startGymWorkout}><input type="hidden" name="plannedWorkoutId" value={nextWorkout.id}/><button className="primary-button">Training starten</button></form> : <Link href={activeProgram ? `/gym/programs/${activeProgram.id}` : "/gym/programs/new"} className="secondary-button">Einplanen</Link>}</div></article>
      <article className="card p-6"><div className="flex items-end justify-between"><div><p className="eyebrow">Aktives Programm</p><h2 className="mt-2 text-xl font-black">{activeProgram?.name ?? "Kein aktives Programm"}</h2></div><Link href={activeProgram ? `/gym/programs/${activeProgram.id}` : "/gym/programs"} className="text-sm font-black text-[var(--accent-dark)]">Öffnen →</Link></div>{activeProgram ? <p className="mt-3 text-sm text-[var(--muted)]">{activeProgram.trainingDaysPerWeek} Trainingstage pro Woche · {activeProgram.goal}</p> : null}</article>
    </section><aside className="space-y-5"><article className="card p-5"><p className="eyebrow">Letzte Einheit</p>{lastSession ? <><h2 className="mt-2 font-black">{lastSession.name}</h2><p className="mt-2 text-sm text-[var(--muted)]">{lastSession.exerciseCount} Übungen · {lastSession.workingSets} Arbeitssätze</p><Link href={`/gym/workout/${lastSession.id}`} className="mt-4 inline-block text-sm font-black text-[var(--accent-dark)]">Zusammenfassung →</Link></> : <p className="mt-2 text-sm text-[var(--muted)]">Noch kein abgeschlossenes Gym-Workout.</p>}</article><article className="card grid grid-cols-2 gap-3 p-4"><Link href="/gym/library" className="rounded-xl bg-[var(--surface)] p-4"><strong className="text-2xl">{overview.exerciseCount}</strong><span className="mt-1 block text-xs font-bold text-[var(--muted)]">Übungen</span></Link><Link href="/gym/programs" className="rounded-xl bg-[var(--surface)] p-4"><strong className="text-2xl">{overview.programs.length}</strong><span className="mt-1 block text-xs font-bold text-[var(--muted)]">Programme</span></Link><Link href="/gym/history" className="col-span-2 rounded-xl bg-[var(--surface)] p-4 font-black">History & Fortschritt →</Link></article></aside></div>}
  </>;
}
