import { PageHeading } from "@/components/page-heading";
import { isDemoMode } from "@/lib/demo-data";
import { getNutritionLibrary, type BottlePreset, type NutritionProduct } from "@/lib/nutrition-planner";
import { removeBottlePreset, removeLibraryProduct, saveBottlePreset, saveLibraryProduct } from "./actions";

export const metadata = { title: "Verpflegung" };
export const dynamic = "force-dynamic";
const inputClass = "mt-1 w-full rounded-xl border border-[var(--line)] bg-white px-3 py-2.5";

function ProductForm({ product }: { product?: NutritionProduct }) {
  return <form action={saveLibraryProduct} className="mt-4 grid gap-3 sm:grid-cols-2"><input type="hidden" name="id" value={product?.id ?? ""} /><label className="text-sm font-semibold">Name<input className={inputClass} name="name" required defaultValue={product?.name} /></label><label className="text-sm font-semibold">Kategorie<select className={inputClass} name="category" defaultValue={product?.category ?? "gel"}><option value="gel">Gel</option><option value="bar">Riegel</option><option value="drink_mix">Getränkepulver</option><option value="food">Lebensmittel</option><option value="other">Sonstiges</option></select></label><label className="text-sm font-semibold">Portion<input className={inputClass} name="servingLabel" defaultValue={product?.servingLabel ?? "1 Stück"} /></label><label className="text-sm font-semibold">Kohlenhydrate (g)<input className={inputClass} name="carbohydrates" type="number" step="0.1" min="0" defaultValue={product?.carbohydratesGrams} /></label><label className="text-sm font-semibold">Flüssigkeit (ml)<input className={inputClass} name="fluid" type="number" step="1" min="0" defaultValue={product?.fluidMilliliters} /></label><label className="text-sm font-semibold">Natrium (mg)<input className={inputClass} name="sodium" type="number" step="1" min="0" defaultValue={product?.sodiumMilligrams} /></label><label className="text-sm font-semibold">Kalorien<input className={inputClass} name="calories" type="number" step="1" min="0" defaultValue={product?.calories} /></label><button className="self-end rounded-xl bg-[var(--accent)] px-4 py-2.5 font-bold text-white" type="submit">{product ? "Änderungen speichern" : "Produkt anlegen"}</button></form>;
}

function PresetForm({ preset }: { preset?: BottlePreset }) {
  return <form action={saveBottlePreset} className="mt-4 grid gap-3 sm:grid-cols-2"><input type="hidden" name="id" value={preset?.id ?? ""} /><label className="text-sm font-semibold sm:col-span-2">Rezeptname<input className={inputClass} name="name" required defaultValue={preset?.name} placeholder="750 ml · 90 g Carbs" /></label><label className="text-sm font-semibold">Volumen (ml)<input className={inputClass} name="volume" type="number" min="1" step="1" defaultValue={preset?.volumeMilliliters ?? 750} /></label><label className="text-sm font-semibold">Kohlenhydrate (g)<input className={inputClass} name="carbohydrates" type="number" min="0" step="0.1" defaultValue={preset?.carbohydratesGrams} /></label><label className="text-sm font-semibold">Natrium (mg)<input className={inputClass} name="sodium" type="number" min="0" step="1" defaultValue={preset?.sodiumMilligrams} /></label><label className="text-sm font-semibold">Kalorien<input className={inputClass} name="calories" type="number" min="0" step="1" defaultValue={preset?.calories} /></label><button className="rounded-xl bg-sky-700 px-4 py-2.5 font-bold text-white sm:col-span-2" type="submit">{preset ? "Rezept speichern" : "Flaschenrezept anlegen"}</button></form>;
}

export default async function NutritionPage({ searchParams }: { searchParams: Promise<{ saved?: string; error?: string }> }) {
  const query = await searchParams;
  const library = await getNutritionLibrary();
  return <><PageHeading title="Verpflegung" description="Deine wiederverwendbare Bibliothek für Produkte und Flaschenrezepte." />{query.saved && <p className="mb-5 rounded-xl bg-emerald-100 px-4 py-3 text-sm font-bold text-emerald-900">Änderung gespeichert.</p>}{query.error && <p className="mb-5 rounded-xl bg-red-100 px-4 py-3 text-sm font-bold text-red-900">{query.error}</p>}{!isDemoMode && !library.ready && <p className="mb-5 rounded-xl bg-amber-100 px-4 py-3 text-sm text-amber-950">Bitte die Migrationen <code>202608020005_nutrition_planner.sql</code> und <code>202608020006_nutrition_library.sql</code> ausführen.</p>}<div className="grid gap-6 xl:grid-cols-2"><section className="card p-6"><h2 className="text-xl font-bold">Produkte</h2><p className="mt-1 text-sm text-[var(--muted)]">Gels, Riegel und Lebensmittel werden in allen Aktivitäten angeboten.</p><div className="mt-5 space-y-3">{library.products.map((product) => <details key={product.id} className="rounded-2xl border border-[var(--line)] p-4"><summary className="cursor-pointer list-none"><span className="font-bold">{product.name}</span><span className="ml-2 text-xs text-[var(--muted)]">{product.carbohydratesGrams} g KH · {product.sodiumMilligrams} mg Na</span></summary><ProductForm product={product} /><form action={removeLibraryProduct.bind(null, product.id)} className="mt-3"><button className="text-sm font-bold text-red-700">Produkt entfernen</button></form></details>)}</div><details open={!library.products.length} className="mt-5 rounded-2xl bg-slate-50 p-4"><summary className="cursor-pointer font-bold">Neues Produkt</summary><ProductForm /></details></section><section className="card p-6"><h2 className="text-xl font-bold">Flaschenrezepte</h2><p className="mt-1 text-sm text-[var(--muted)]">Inhalt einmal speichern, bei einer Aktivität nur noch Zeitplan und Restmenge wählen.</p><div className="mt-5 space-y-3">{library.presets.map((preset) => <details key={preset.id} className="rounded-2xl border border-sky-200 bg-sky-50 p-4"><summary className="cursor-pointer list-none"><span className="font-bold">{preset.name}</span><span className="ml-2 text-xs text-[var(--muted)]">{preset.volumeMilliliters} ml · {preset.carbohydratesGrams} g KH</span></summary><PresetForm preset={preset} /><form action={removeBottlePreset.bind(null, preset.id)} className="mt-3"><button className="text-sm font-bold text-red-700">Rezept entfernen</button></form></details>)}</div><details open={!library.presets.length} className="mt-5 rounded-2xl bg-sky-50 p-4"><summary className="cursor-pointer font-bold">Neues Flaschenrezept</summary><PresetForm /></details></section></div></>;
}

