import { deleteBottlePlan, deleteNutritionProduct, saveBottlePlan, saveNutritionProduct } from "@/app/activities/[id]/actions";
import { NutritionTimeline } from "@/components/nutrition-timeline";
import type { NutritionEntry } from "@/lib/nutrition-analysis";
import type { BottlePlan, BottlePreset, NutritionProduct } from "@/lib/nutrition-planner";
import { formatDuration } from "@/lib/format";

const inputClass = "mt-1.5 w-full rounded-xl border border-[var(--line)] bg-white px-3 py-2.5 outline-none focus:border-[var(--accent)]";

export function NutritionPlanner({ activityId, elapsedTimeSeconds, products, bottles, presets, entries, editable, ready }: { activityId: string; elapsedTimeSeconds: number; products: NutritionProduct[]; bottles: BottlePlan[]; presets: BottlePreset[]; entries: NutritionEntry[]; editable: boolean; ready: boolean }) {
  if (!editable) return null;
  if (!ready) return <section className="card mt-6 p-6"><h2 className="text-lg font-bold">Schnelle Verpflegungsplanung</h2><p className="mt-4 rounded-xl bg-amber-100 px-4 py-3 text-sm text-amber-950">Bitte zuerst die Migrationen <code>202608020005_nutrition_planner.sql</code> und <code>202608020006_nutrition_library.sql</code> im Supabase SQL Editor ausführen.</p></section>;
  const lastHours = Math.floor(elapsedTimeSeconds / 3600);
  const lastMinutes = Math.floor(elapsedTimeSeconds % 3600 / 60);
  return (
    <section className="card mt-6 p-6">
      <div><p className="text-xs font-bold uppercase tracking-[.16em] text-[var(--accent)]">Schneller protokollieren</p><h2 className="mt-1 text-xl font-bold">Produkte & Trinkplan</h2><p className="mt-1 text-sm text-[var(--muted)]">Produkte einmal speichern, danach nur noch Zeitpunkt und Produkt antippen.</p></div>
      <div className="mt-6"><NutritionTimeline activityId={activityId} elapsedTimeSeconds={elapsedTimeSeconds} products={products} entries={entries} /></div>
      <div className="mt-6 grid gap-6 xl:grid-cols-2">
        <div>
          <h3 className="font-bold">Meine Produkte</h3>
          <div className="mt-3 space-y-2">{products.map((product) => <div key={product.id} className="flex items-center justify-between gap-3 rounded-xl border border-[var(--line)] p-3"><div><p className="font-semibold">{product.name}</p><p className="text-xs text-[var(--muted)]">{product.servingLabel} · {product.carbohydratesGrams} g KH · {product.sodiumMilligrams} mg Natrium</p></div><form action={deleteNutritionProduct.bind(null, activityId, product.id)}><button className="text-xs font-bold text-red-700" type="submit">Entfernen</button></form></div>)}{!products.length && <p className="text-sm text-[var(--muted)]">Noch keine Produkte gespeichert.</p>}</div>
          <details className="mt-4 rounded-2xl border border-[var(--line)] p-4"><summary className="cursor-pointer font-bold">Neues Produkt anlegen</summary><form action={saveNutritionProduct.bind(null, activityId)} className="mt-4"><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Produktname<input className={inputClass} name="Produktname" required placeholder="z. B. Maurten Gel 100" /></label><label className="text-sm font-semibold">Kategorie<select className={inputClass} name="Kategorie" defaultValue="gel"><option value="gel">Gel</option><option value="bar">Riegel</option><option value="drink_mix">Getränkepulver</option><option value="food">Lebensmittel</option><option value="other">Sonstiges</option></select></label><label className="text-sm font-semibold">Bezeichnung der Portion<input className={inputClass} name="Portion" defaultValue="1 Stück" /></label><label className="text-sm font-semibold">Kohlenhydrate pro Portion (g)<input className={inputClass} name="Produkt Kohlenhydrate" type="number" min="0" step="0.1" /></label><label className="text-sm font-semibold">Flüssigkeit (ml)<input className={inputClass} name="Produkt Flüssigkeit" type="number" min="0" step="1" /></label><label className="text-sm font-semibold">Natrium (mg)<input className={inputClass} name="Produkt Natrium" type="number" min="0" step="1" /></label><label className="text-sm font-semibold">Kalorien<input className={inputClass} name="Produkt Kalorien" type="number" min="0" step="1" /></label></div><button className="mt-4 rounded-xl bg-[var(--accent)] px-4 py-2.5 font-bold text-white" type="submit">Produkt speichern</button><p className="mt-3 text-xs text-[var(--muted)]">Das Schema enthält bereits Felder für spätere Foto- und Barcode-Erkennung. Diese Phase übernimmt noch keine Fotos.</p></form></details>
        </div>
        <div>
          <h3 className="font-bold">Flaschen dieser Aktivität</h3>
          {presets.length > 0 && <div className="mt-3 rounded-2xl bg-sky-50 p-4"><p className="text-sm font-bold">Gespeichertes Rezept anwenden</p><div className="mt-3 space-y-2">{presets.map((preset) => <details key={preset.id} className="rounded-xl bg-white p-3"><summary className="cursor-pointer text-sm font-semibold">{preset.name} · {preset.volumeMilliliters} ml · {preset.carbohydratesGrams} g KH</summary><form action={saveBottlePlan.bind(null, activityId)} className="mt-3 grid grid-cols-2 gap-3"><input type="hidden" name="presetId" value={preset.id} /><label className="text-xs">Intervall (min)<input className={inputClass} name="Intervall" type="number" min="5" max="240" defaultValue="20" /></label><label className="text-xs">Rest (%)<input className={inputClass} name="Restmenge" type="number" min="0" max="99" defaultValue="0" /></label><label className="text-xs">Erster Schluck Stunden<input className={inputClass} name="Erster Schluck Stunden" type="number" min="0" defaultValue="0" /></label><label className="text-xs">Minuten<input className={inputClass} name="Erster Schluck Minuten" type="number" min="0" max="59" defaultValue="20" /></label><label className="text-xs">Letzter Schluck Stunden<input className={inputClass} name="Letzter Schluck Stunden" type="number" min="0" defaultValue={lastHours} /></label><label className="text-xs">Minuten<input className={inputClass} name="Letzter Schluck Minuten" type="number" min="0" max="59" defaultValue={lastMinutes} /></label><button className="col-span-2 rounded-xl bg-sky-700 px-4 py-2.5 text-sm font-bold text-white" type="submit">Für diese Tour eintragen</button></form></details>)}</div></div>}
          <div className="mt-3 space-y-2">{bottles.map((bottle) => <div key={bottle.id} className="rounded-xl border border-sky-200 bg-sky-50 p-3"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{bottle.name}</p><p className="mt-1 text-xs text-sky-950/70">{bottle.volumeMilliliters} ml · {bottle.carbohydratesGrams} g KH · alle {bottle.intervalMinutes} min</p><p className="text-xs text-sky-950/70">{formatDuration(bottle.firstDrinkSeconds)}–{formatDuration(bottle.lastDrinkSeconds)} · {bottle.remainingPercent === 0 ? "am Ende leer" : `${bottle.remainingPercent} % übrig`}</p></div><form action={deleteBottlePlan.bind(null, activityId, bottle.id)}><button className="text-xs font-bold text-red-700" type="submit">Löschen</button></form></div><p className="mt-2 text-xs font-semibold text-sky-900">Zeitpunkte rechnerisch gleichmäßig verteilt</p></div>)}{!bottles.length && <p className="text-sm text-[var(--muted)]">Noch keine Flasche für diese Tour eingetragen.</p>}</div>
          <details className="mt-4 rounded-2xl border border-[var(--line)] p-4"><summary className="cursor-pointer font-bold">Flasche und Trinkintervall anlegen</summary><form action={saveBottlePlan.bind(null, activityId)} className="mt-4"><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold sm:col-span-2">Name<input className={inputClass} name="Flaschenname" defaultValue="Iso-Flasche" /></label><label className="text-sm font-semibold">Volumen (ml)<input className={inputClass} name="Flaschenvolumen" type="number" min="1" step="1" defaultValue="750" /></label><label className="text-sm font-semibold">Kohlenhydrate gesamt (g)<input className={inputClass} name="Flasche Kohlenhydrate" type="number" min="0" step="0.1" /></label><label className="text-sm font-semibold">Natrium gesamt (mg)<input className={inputClass} name="Flasche Natrium" type="number" min="0" step="1" /></label><label className="text-sm font-semibold">Kalorien gesamt<input className={inputClass} name="Flasche Kalorien" type="number" min="0" step="1" /></label><label className="text-sm font-semibold">Alle wie viele Minuten?<input className={inputClass} name="Intervall" type="number" min="5" max="240" step="1" defaultValue="20" /></label><label className="text-sm font-semibold">Rest am Ende (%)<input className={inputClass} name="Restmenge" type="number" min="0" max="100" step="1" defaultValue="0" /></label><fieldset className="sm:col-span-2"><legend className="text-sm font-bold">Erster Schluck</legend><div className="grid grid-cols-2 gap-3"><label className="text-xs">Stunden<input className={inputClass} name="Erster Schluck Stunden" type="number" min="0" step="1" defaultValue="0" /></label><label className="text-xs">Minuten<input className={inputClass} name="Erster Schluck Minuten" type="number" min="0" max="59" step="1" defaultValue="20" /></label></div></fieldset><fieldset className="sm:col-span-2"><legend className="text-sm font-bold">Letzter Schluck / Ende</legend><div className="grid grid-cols-2 gap-3"><label className="text-xs">Stunden<input className={inputClass} name="Letzter Schluck Stunden" type="number" min="0" step="1" defaultValue={lastHours} /></label><label className="text-xs">Minuten<input className={inputClass} name="Letzter Schluck Minuten" type="number" min="0" max="59" step="1" defaultValue={lastMinutes} /></label></div></fieldset></div><div className="mt-4 rounded-xl bg-amber-50 p-3 text-xs leading-5 text-amber-950">Mit dem Speichern bestätigst du: UltraPilot darf die tatsächlich getrunkene Gesamtmenge gleichmäßig auf die angegebenen Zeitpunkte verteilen. Diese Werte werden als abgeleitet markiert.</div><button className="mt-4 rounded-xl bg-sky-700 px-4 py-2.5 font-bold text-white" type="submit">Flaschenplan erstellen</button></form></details>
        </div>
      </div>
    </section>
  );
}
