"use client";

import { Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { RecoveryTrendPoint } from "@/lib/recovery-analysis";

function dateLabel(value: string): string {
  return new Intl.DateTimeFormat("de-DE", { day: "2-digit", month: "2-digit" }).format(new Date(`${value}T12:00:00Z`));
}

const statusColor = { green: "#2563eb", yellow: "#e8a53a", red: "#df5a67", unknown: "#cbd5e1" } as const;
const tooltipStyle = { border: "1px solid #dce6f2", borderRadius: 12 };

export function RecoveryCharts({ trend }: { trend: RecoveryTrendPoint[] }) {
  return <section className="mt-6 grid gap-6 xl:grid-cols-2">
    <article className="card p-5"><h2 className="font-bold">Schlafphasen</h2><p className="mt-1 text-xs text-[var(--muted)]">Tatsächlich erkannte Schlafzeit pro Nacht · Lücken bleiben sichtbar</p><div className="mt-4 h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={trend} margin={{ top: 8, right: 8, bottom: 0, left: 0 }}><CartesianGrid stroke="#e3ebf6" strokeDasharray="4 4" vertical={false}/><XAxis dataKey="date" tickFormatter={dateLabel} minTickGap={24} tick={{ fill: "#65758b", fontSize: 11 }} axisLine={false} tickLine={false}/><YAxis unit=" h" tick={{ fill: "#65758b", fontSize: 11 }} axisLine={false} tickLine={false}/><Tooltip labelFormatter={(label) => dateLabel(String(label))} formatter={(value, name) => [`${Number(value).toFixed(1)} h`, String(name)]} contentStyle={tooltipStyle}/><Legend/><Bar stackId="sleep" dataKey="coreHours" name="Core" fill="#38bdf8"/><Bar stackId="sleep" dataKey="deepHours" name="Tief" fill="#6366f1"/><Bar stackId="sleep" dataKey="remHours" name="REM" fill="#8b5cf6"/><Bar stackId="sleep" dataKey="unspecifiedHours" name="Ohne Phase" fill="#94a3b8" radius={[5, 5, 0, 0]}/></BarChart></ResponsiveContainer></div></article>

    <article className="card p-5"><h2 className="font-bold">Nächtliche HF und HRV</h2><p className="mt-1 text-xs text-[var(--muted)]">Persönlicher Verlauf · keine Verbindung über fehlende Messnächte</p><div className="mt-4 h-72"><ResponsiveContainer width="100%" height="100%"><LineChart data={trend} margin={{ top: 8, right: 10, bottom: 0, left: 0 }}><CartesianGrid stroke="#e3ebf6" strokeDasharray="4 4" vertical={false}/><XAxis dataKey="date" tickFormatter={dateLabel} minTickGap={24} tick={{ fill: "#65758b", fontSize: 11 }} axisLine={false} tickLine={false}/><YAxis yAxisId="heartRate" unit=" bpm" domain={["auto", "auto"]} tick={{ fill: "#65758b", fontSize: 11 }} axisLine={false} tickLine={false}/><YAxis yAxisId="hrv" orientation="right" unit=" ms" domain={[0, "auto"]} tick={{ fill: "#65758b", fontSize: 11 }} axisLine={false} tickLine={false}/><Tooltip labelFormatter={(label) => dateLabel(String(label))} formatter={(value, name) => [`${Number(value).toFixed(1)} ${String(name).includes("HRV") ? "ms" : "bpm"}`, String(name)]} contentStyle={tooltipStyle}/><Legend/><Line yAxisId="heartRate" type="monotone" dataKey="sleepingAverageHeartRate" name="Ø HF nachts" stroke="#d85d68" strokeWidth={3} dot={{ r: 3 }} connectNulls={false} isAnimationActive={false}/><Line yAxisId="heartRate" type="monotone" dataKey="sleepingMinimumHeartRate" name="Minimum HF" stroke="#ef9a9f" strokeWidth={2} strokeDasharray="4 4" dot={false} connectNulls={false} isAnimationActive={false}/><Line yAxisId="hrv" type="monotone" dataKey="hrvSdnnMs" name="HRV (SDNN)" stroke="#2563eb" strokeWidth={3} dot={{ r: 3 }} connectNulls={false} isAnimationActive={false}/></LineChart></ResponsiveContainer></div></article>

    <article className="card p-5 xl:col-span-2"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="font-bold">Readiness-Verlauf</h2><p className="mt-1 text-xs text-[var(--muted)]">Schlaf, persönlicher HF-/HRV-Verlauf und Check-in · regelbasiert, nicht medizinisch</p></div><div className="flex gap-3 text-xs text-[var(--muted)]"><span><i className="mr-1 inline-block size-2 rounded-full bg-emerald-500"/>Grün</span><span><i className="mr-1 inline-block size-2 rounded-full bg-amber-400"/>Gelb</span><span><i className="mr-1 inline-block size-2 rounded-full bg-rose-500"/>Rot</span></div></div><div className="mt-4 h-56"><ResponsiveContainer width="100%" height="100%"><BarChart data={trend} margin={{ top: 8, right: 8, bottom: 0, left: 0 }}><CartesianGrid stroke="#e3ebf6" strokeDasharray="4 4" vertical={false}/><XAxis dataKey="date" tickFormatter={dateLabel} minTickGap={24} tick={{ fill: "#65758b", fontSize: 11 }} axisLine={false} tickLine={false}/><YAxis domain={[0, 100]} tick={{ fill: "#65758b", fontSize: 11 }} axisLine={false} tickLine={false}/><Tooltip labelFormatter={(label) => dateLabel(String(label))} formatter={(value) => [`${Number(value)} / 100`, "Readiness"]} contentStyle={tooltipStyle}/><Bar dataKey="readinessScore" name="Readiness" radius={[5, 5, 0, 0]}>{trend.map((item) => <Cell key={item.date} fill={statusColor[item.readinessStatus]}/>)}</Bar></BarChart></ResponsiveContainer></div></article>
  </section>;
}
