"use client";

import { Bar, CartesianGrid, Cell, ComposedChart, Legend, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { TrainingLoadTrend } from "@/lib/training-load";

const colors = { light: "#38bdf8", moderate: "#e8a53a", high: "#df5a67", unavailable: "#cbd5e1" } as const;
function dateLabel(value: string): string { return new Intl.DateTimeFormat("de-DE", { day: "2-digit", month: "2-digit" }).format(new Date(`${value}T12:00:00Z`)); }

export function TrainingLoadCharts({ trend }: { trend: TrainingLoadTrend[] }) {
  return <article className="card mt-6 p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="font-bold">Trainingsbelastung</h2><p className="mt-1 text-xs text-[var(--muted)]">Tageslast und rollierende 7-Tage-Summe in UltraPilot Load Points</p></div><div className="flex gap-3 text-xs text-[var(--muted)]"><span><i className="mr-1 inline-block size-2 rounded-full bg-[#38bdf8]"/>leicht</span><span><i className="mr-1 inline-block size-2 rounded-full bg-[#e8a53a]"/>mittel</span><span><i className="mr-1 inline-block size-2 rounded-full bg-[#df5a67]"/>hoch</span></div></div><div className="mt-4 h-72"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={trend} margin={{ top: 8, right: 12, bottom: 0, left: 0 }}><CartesianGrid stroke="#e3ebf6" strokeDasharray="4 4" vertical={false}/><XAxis dataKey="date" tickFormatter={dateLabel} minTickGap={24} tick={{ fill: "#65758b", fontSize: 11 }} axisLine={false} tickLine={false}/><YAxis yAxisId="daily" tick={{ fill: "#65758b", fontSize: 11 }} axisLine={false} tickLine={false}/><YAxis yAxisId="rolling" orientation="right" tick={{ fill: "#65758b", fontSize: 11 }} axisLine={false} tickLine={false}/><Tooltip labelFormatter={(label) => dateLabel(String(label))} formatter={(value, name) => [`${Number(value).toFixed(1)} UPL`, String(name)]} contentStyle={{ border: "1px solid #dce6f2", borderRadius: 12 }}/><Legend/><Bar yAxisId="daily" dataKey="loadPoints" name="Tageslast" radius={[5, 5, 0, 0]}>{trend.map((item) => <Cell key={item.date} fill={colors[item.level]}/>)}</Bar><Line yAxisId="rolling" type="monotone" dataKey="rollingSevenDayLoad" name="7-Tage-Summe" stroke="#1d4ed8" strokeWidth={3} dot={false} isAnimationActive={false}/></ComposedChart></ResponsiveContainer></div></article>;
}
