import Link from "next/link";
import type { Activity } from "@/lib/demo-data";
import type { TrainingBlock } from "@/lib/planning/blocks";
import { completeTrainingBlock, createTrainingBlock } from "@/app/plan/block-actions";

const phaseLabels = { foundation: "Grundlage", build: "Aufbau", peak: "Belastung", recovery: "Erholung" } as const;
const phaseStyles = { foundation: "bg-emerald-100 text-emerald-950", build: "bg-sky-100 text-sky-950", peak: "bg-amber-100 text-amber-950", recovery: "bg-violet-100 text-violet-950" } as const;
const inputClass = "mt-1.5 w-full rounded-xl border border-[var(--line)] bg-white px-3 py-2.5";

function localDate(value: string): string {
  return new Intl.DateTimeFormat("sv-SE", { timeZone: "Europe/Berlin", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date(value));
}

export function TrainingBlockOverview({ block, selectedWeek, activities, weeklyDistanceKm, editable }: { block: TrainingBlock | null; selectedWeek: string; activities: Activity[]; weeklyDistanceKm: number; editable: boolean }) {
  if (!block) return <section className="card mb-4 p-6"><div className="grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Vier-Wochen-Plan</p><h2 className="mt-2 text-2xl font-black">Deinen ersten Grundlagenblock starten</h2><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Die lange Ausfahrt wächst zwei Wochen kontrolliert, Woche 3 setzt den höchsten Reiz und Woche 4 reduziert die Intensität. Dienste, Readiness und Belastung entscheiden weiterhin über die konkreten Trainingstage.</p></div><form action={createTrainingBlock} className="grid gap-4 sm:grid-cols-2"><input type="hidden" name="selectedWeek" value={selectedWeek}/><label className="text-sm font-bold sm:col-span-2">Name<input name="name" required maxLength={120} defaultValue="Grundlagenblock 1" className={inputClass}/></label><label className="text-sm font-bold">Startmontag<input name="startDate" type="date" required defaultValue={selectedWeek} className={inputClass}/></label><label className="text-sm font-bold">Normale Wochenkilometer<input name="weeklyDistanceKm" type="number" min="20" max="2000" step="1" required defaultValue={weeklyDistanceKm} className={inputClass}/></label><label className="text-sm font-bold">Erste lange Fahrt (km)<input name="startingLongRideKm" type="number" min="10" max="1000" step="1" required defaultValue={Math.round(weeklyDistanceKm * .4)} className={inputClass}/></label><label className="text-sm font-bold">Erholungswoche<select name="recoveryWeekPercentage" defaultValue="100" className={inputClass}><option value="100">100 % · 125-km-Ziel erhalten</option><option value="90">90 % Umfang</option><option value="80">80 % Umfang</option><option value="70">70 % Umfang</option><option value="60">60 % Umfang</option></select></label><button disabled={!editable} className="rounded-xl bg-[var(--accent)] px-5 py-3 font-bold text-white disabled:opacity-50 sm:col-span-2">Vier-Wochen-Block erstellen</button></form></div></section>;

  return <section className="card mb-4 p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">Aktiver Trainingsblock</p><h2 className="mt-2 text-2xl font-black">{block.name}</h2><p className="mt-1 text-sm text-[var(--muted)]">{new Intl.DateTimeFormat("de-DE", { day: "numeric", month: "short" }).format(new Date(`${block.startDate}T12:00:00`))} – {new Intl.DateTimeFormat("de-DE", { day: "numeric", month: "short", year: "numeric" }).format(new Date(`${block.endDate}T12:00:00`))}</p></div><form action={completeTrainingBlock}><input type="hidden" name="id" value={block.id}/><input type="hidden" name="selectedWeek" value={selectedWeek}/><button className="rounded-xl border border-[var(--line)] bg-white px-4 py-2 text-sm font-bold text-[var(--muted)] hover:bg-slate-50">Block abschließen</button></form></div><div className="mt-5 grid gap-3 lg:grid-cols-4">{block.weeks.map((week) => { const end = new Date(`${week.weekStart}T12:00:00Z`); end.setUTCDate(end.getUTCDate() + 6); const actualKm = activities.filter((activity) => { const date = localDate(activity.activityDate); return date >= week.weekStart && date <= end.toISOString().slice(0, 10); }).reduce((sum, activity) => sum + activity.distanceMeters / 1000, 0); const progress = Math.min(100, week.targetDistanceKm > 0 ? actualKm / week.targetDistanceKm * 100 : 0); return <Link key={week.id} href={`/plan?week=${week.weekStart}`} className={`rounded-2xl border p-4 transition hover:-translate-y-0.5 hover:shadow-md ${selectedWeek === week.weekStart ? "border-[var(--accent)] bg-emerald-50 ring-2 ring-emerald-900/5" : "border-[var(--line)] bg-white/70"}`}><div className="flex items-center justify-between gap-2"><p className="text-xs font-black uppercase tracking-wider">Woche {week.weekNumber}</p><span className={`rounded-full px-2 py-1 text-[.65rem] font-black ${phaseStyles[week.phase]}`}>{phaseLabels[week.phase]}</span></div><p className="mt-4 text-2xl font-black">{week.targetDistanceKm.toLocaleString("de-DE", { maximumFractionDigits: 0 })} km</p><p className="mt-1 text-xs text-[var(--muted)]">Lange Fahrt {week.longRideTargetKm.toLocaleString("de-DE", { maximumFractionDigits: 1 })} km · {week.tempoSessionTarget ? "1× Tempo" : "kein Tempo"}</p><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-[var(--accent)]" style={{ width: `${progress}%` }}/></div><p className="mt-2 text-xs font-bold text-[var(--muted)]">{actualKm.toLocaleString("de-DE", { maximumFractionDigits: 1 })} km absolviert</p><p className="mt-3 text-xs leading-5 text-[var(--muted)]">{week.purpose}</p></Link>; })}</div></section>;
}
